// frontend/pages/login.tsx
import { NextPage } from "next";
import styles from "../styles/authform.module.scss";
import Logo from "../public/logo.png";
import { SubmitHandler, useForm } from "react-hook-form";
import Link from "next/link";
import Head from "next/head";

interface IFormInputs {
  email: string;
  password: string;
}

const Login: NextPage = () => {
  const {
    register,
    formState: { errors },
    handleSubmit,
  } = useForm<IFormInputs>();
  const onSubmit: SubmitHandler<IFormInputs> = () => {}; // TODO: implement log in

  return (
    <div className={"flex justify-center items-center h-screen"}>
      <Head>
        <title>Log In - NerdTree</title>
      </Head>
      <div className={styles["login-form"]}>
        <div>
          <img
            className={"bg-black rounded-full"}
            src={Logo.src}
            alt={"NerdTree Logo"}
          />
        </div>
        <Link href={"/"}>
          <h1 className={"cursor-pointer"}>NerdTree</h1>
        </Link>
        <form onSubmit={handleSubmit(onSubmit)}>
          <div className={styles["input-container"]}>
            <label className={"block"}>Email</label>
            <input
              className={errors.email && styles["contains-error"]}
              type={"email"}
              placeholder={"user@example.com"}
              {...register("email", {
                required: true,
                pattern: /^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/g,
              })}
            />
            <span className={styles["error-info"]}>
              {errors.email && "Invalid or missing email"}
            </span>
          </div>
          <div className={styles["input-container"]}>
            <label className={"block"}>Password</label>
            <input
              className={errors.password && styles["contains-error"]}
              type={"password"}
              placeholder={"Your Password"}
              {...register("password", { required: true })}
            />
            <span className={styles["error-info"]}>
              {errors.password && "Password is required"}
            </span>
          </div>
          <div className={"flex justify-end"}>
            <input
              className={styles["action-button"]}
              type={"submit"}
              value={"Log In"}
            />
          </div>
          <div className={"flex justify-center"}>
            <Link href={"/register"}>
              <span className={`${styles["other-form-link"]} cursor-pointer`}>
                Join NerdTree
              </span>
            </Link>
          </div>
        </form>
      </div>
    </div>
  );
};

export default Login;

// frontend-svelte/src/routes/login/+page.svelte
<script lang="ts">
    import * as yup from 'yup';
    import { createForm } from 'svelte-forms-lib';
    import { API } from '../../api_wrapper';
    import { goto } from '$app/navigation';
    import '../../styles/authform.scss';
    import Logo from '../../images/logo.png';
    import {AuthenticationStatus} from "../../stores/user";

    AuthenticationStatus.subscribe(status => {
        if (status.info) {
            goto("/", { replaceState: true });
        }
    });

    let loginError = "";
    const { form, errors, isValid, handleSubmit, touched, isSubmitting } = createForm({
        initialValues: {
            Username: '',
            Password: ''
        },
        validationSchema: yup.object().shape({
            Username: yup.string().required(),
            Password: yup.string().required()
        }),
        onSubmit: async (values) => {
            const result = await API.auth.login({
                username: values.Username,
                password: values.Password
            });

            if (result.success) {
                await goto("/", { replaceState: true })
            } else {
                loginError = result.error;
            }
        }
    });
</script>

<svelte:head>
    <title>Log In - NerdTree</title>
</svelte:head>

<div class="flex justify-center items-center h-screen">
    <div class="form-container">
        <div>
            <img class="bg-black rounded-full" src={Logo} alt="NerdTree logo" />
        </div>
        <a href="/">
            <h1>NerdTree</h1>
        </a>
        {#if loginError}
            <span class="error-info">{loginError}</span>
        {/if}
        <form class:valid={$isValid} on:submit={handleSubmit}>
            <div class="input-container">
                <label class="block" for="Username">Username</label>
                <input
                    id="Username"
                    class={$errors.Username && 'contains-error'}
                    name="Username"
                    placeholder="user1234"
                    bind:value={$form.Username}
                />
                {#if $errors.Username && $touched.Username}
                    <span class="error-info">{$errors.Username}</span>
                {/if}
            </div>
            <div class="input-container">
                <label class="block" for="Password">Password</label>
                <input
                    class={$errors.Password && 'contains-error'}
                    name="Password"
                    id="Password"
                    type="password"
                    placeholder="password1234"
                    bind:value={$form.Password}
                />
                {#if $errors.Password && $touched.Password}
                    <span class="error-info">{$errors.Password}</span>
                {/if}
            </div>
            <div class="flex justify-end">
                <input
                    class="action-button"
                    type="submit"
                    value={`${$isSubmitting ? 'Logging in...' : 'Log In'}`}
                />
            </div>
            <div class="flex justify-center">
                <a href="/register">
                    <span class="other-form-link cursor-pointer">Join NerdTree</span>
                </a>
            </div>
        </form>
    </div>
</div>
