// frontend/components/blog_card.tsx
import { User } from "../interfaces/user";
import styles from "../styles/blog_card.module.scss";
import Link from "next/link";

interface Props {
  blog_id: string;
  blog_title: string;
  blog_image: string;
  blog_votes: number;
  blog_author: User | null;
}

function round_number(n: number): string {
  let is_negative = n < 0;
  let abs_n = Math.abs(n);
  let result = is_negative ? "-" : "";

  if (abs_n / 1_000_000 >= 1) {
    result += `${(abs_n / 1_000_000).toFixed(2)}m`;
  } else if (abs_n / 1000 >= 1) {
    result += `${(abs_n / 1000).toFixed(2)}k`;
  } else {
    result += abs_n;
  }

  return result;
}

const BlogCard = (props: Props) => {
  return (
    <div className={styles["blog-card"]}>
      <Link
        href={`/u/${
          props.blog_author ? props.blog_author.username : "deleted_user"
        }`}
      >
        <h3>
          u/{props.blog_author ? props.blog_author.username : "deleted_user"}
        </h3>
      </Link>
      <Link href={`/blogs/${props.blog_id}`}>
        <h1>{props.blog_title}</h1>
      </Link>
      <h4>{`${round_number(props.blog_votes)} upvotes`}</h4>
      <img src={props.blog_image} alt={"Blog Thumbnail"} />
    </div>
  );
};

export default BlogCard;

// frontend/src/components/blog_card.svelte
<script lang="ts">
    import type { User } from '../interfaces/user';
    import {onMount} from "svelte";
    import {API} from "../api_wrapper";

    export let blog_id: string;
    export let blog_title: string;
    export let blog_image: string | null;
    export let blog_author: string | null;

    let blog_votes = 0;
    let author: User | null = null;

    onMount(async () => {
        {
            const result = await API.user.query.id({
                id: blog_author
            });

            if (result.success) {
                author = result.value;
            }
        }

        {
            const result = await API.post.vote.votes({
                post_id: blog_id,
            });

            if (result.success) {
                blog_votes = result.value.votes;
            }
        }
    });

    function round_number(n: number): string {
        let abs_n = Math.abs(n);
        let result = n < 0 ? '-' : '';

        if (abs_n / 1_000_000 >= 1) {
            result += `${(abs_n / 1_000_000).toFixed(1)}m`;
        } else if (abs_n / 1000 >= 1) {
            result += `${(abs_n / 1000).toFixed(1)}k`;
        } else {
            result += abs_n;
        }

        return result;
    }
</script>

<div class="blog-card">
    <a href={`/u/${author ? author.username : 'deleted_user'}`}>
        <h3>
            u/{author ? author.username : 'deleted_user'}
        </h3>
    </a>
    <a href={`/blogs/${blog_id}`}>
        <h1>{blog_title}</h1>
    </a>
    <h4>{`${round_number(blog_votes)} upvotes`}</h4>
    <img src={blog_image ? blog_image : "https://via.placeholder.com/600x400" } alt={'Blog Thumbnail'} />
</div>

<style lang="scss">
    .blog-card {
        max-width: 400px;
        background: linear-gradient(
            223.22deg,
            rgba(109, 109, 109, 0.42) -23.79%,
            rgba(255, 255, 255, 0) 100.29%
        );
        border: 1px solid rgba(255, 255, 255, 0.24);
        border-radius: 18px;
        padding: 1.5em;
        display: flex;
        flex-direction: column;
        flex-basis: 300px;
        flex-shrink: 0;
        gap: 5px;
        height: min-content;

        img {
            width: 100%;
            border-radius: 18px;
        }

        h1,
        h3 {
            user-select: none;
            cursor: pointer;
        }

        h3 {
            color: #bdbdbd;
        }
    }
</style>
