// frontend-svelte/src/components/footer.svelte
<script>
    import '../styles/footer.scss';
</script>

<div class="footer flex items-center justify-between p-2 pl-5 pr-5">
    <h1>NerdTree</h1>
    <div>
        <a href="https://github.com/NerdTree-Org/nerdtree">Github</a>
        <a href="https://facebook.com/nerdtree">Facebook</a>
        <a href="https://discord.gg/EKsmr9UBfD">Discord</a>
    </div>
</div>

// frontend/components/footer.tsx
import styles from "../styles/footer.module.scss";
import Link from "next/link";

const Footer = () => {
  return (
    <div className={styles["footer"]}>
      <h1>NerdTree</h1>
      <div>
        <Link href={"https://github.com/NerdTree-Org/NerdTree"}>Github</Link>
        <Link href={"https://www.facebook.com/nerdtree"}>Facebook</Link>
        <Link href={"https://discord.gg/EKsmr9UBfD"}>Discord</Link>
      </div>
    </div>
  );
};

export default Footer;
