// frontend/src/routes/register/+page.svelte
<script lang="ts">
    import '../../styles/authform.scss';
    import { goto } from '$app/navigation';
    import { AuthenticationStatus } from '../../stores/user';
    import Logo from '../../images/logo.png';
    import { createForm } from 'svelte-forms-lib';
    import * as yup from 'yup';
    import { get } from 'svelte/store';
    import { API } from '../../api_wrapper';

    let registrationInfo;
    let registrationError;
    let firstPart = true;

    const { form, errors, isValid, handleSubmit, touched, isSubmitting, validateField } =
        createForm({
            initialValues: {
                Firstname: '',
                Lastname: '',
                FacebookID: '',
                Email: '',
                Username: '',
                Password: '',
                ConfirmPassword: ''
            },
            validationSchema: yup.object({
                Firstname: yup.string().trim().min(3).max(255).required(),
                Lastname: yup.string().trim().min(3).max(255).required(),
                FacebookID: yup.string().trim().max(80).required(),
                Email: yup.string().trim().email().required(),
                Username: yup.string().trim().min(3).max(25).required(),
                Password: yup.string().trim().min(8).max(80).required(),
                ConfirmPassword: yup.string().trim().min(8).max(80).required()
            }),
            onSubmit: async (values) => {
                if (values.ConfirmPassword !== values.Password) {
                    errors.set({
                        ...get(errors),
                        ConfirmPassword: "Must be equal to 'Password' field"
                    });
                    return;
                }

                const result = await API.auth.register({
                    firstname: values.Firstname,
                    lastname: values.Lastname,
                    username: values.Username,
                    email: values.Email,
                    facebook_id: values.FacebookID,
                    password: values.Password
                });

                if (result.success) {
                    $form = {};
                    registrationInfo =
                        'Registered successfully! Please go to login page to log into your new account';
                    registrationError = '';
                } else {
                    registrationInfo = '';
                    registrationError = result.error;
                }
                firstPart = true;
            }
        });

    AuthenticationStatus.subscribe((status) => {
        if (status.info) {
            goto('/', { replaceState: true });
        }
    });
</script>

<svelte:head>
    <title>Register - NerdTree</title>
</svelte:head>

<div class="flex justify-center items-center h-screen">
    <div class="form-container">
        <div>
            <img class="bg-black rounded-full" src={Logo} alt="NerdTree logo" />
        </div>
        <a href="/">
            <h1>NerdTree</h1>
        </a>
        {#if registrationError}
            <span class="error-info">{registrationError}</span>
        {:else if registrationInfo}
            <span class="text-center">{registrationInfo}</span>
        {/if}
        <form class:valid={isValid} on:submit={handleSubmit}>
            <div class={!firstPart && 'hidden'}>
                <div class="input-container">
                    <label class="block" for="Firstname">Firstname</label>
                    <input
                        id="Firstname"
                        class={$errors.Firstname && 'contains-error'}
                        name="Firstname"
                        placeholder="John"
                        bind:value={$form.Firstname}
                    />
                    {#if $errors.Firstname}
                        <span class="error-info">{$errors.Firstname}</span>
                    {/if}
                </div>
                <div class="input-container">
                    <label class="block" for="Lastname">Lastname</label>
                    <input
                        id="Lastname"
                        class={$errors.Lastname && 'contains-error'}
                        name="Lastname"
                        placeholder="Doe"
                        bind:value={$form.Lastname}
                    />
                    {#if $errors.Lastname}
                        <span class="error-info">{$errors.Lastname}</span>
                    {/if}
                </div>
                <div class="input-container">
                    <label class="block" for="Email">Email</label>
                    <input
                        id="Email"
                        class={$errors.Email && 'contains-error'}
                        name="Email"
                        placeholder="johndoe@example.com"
                        bind:value={$form.Email}
                    />
                    {#if $errors.Email}
                        <span class="error-info">{$errors.Email}</span>
                    {/if}
                </div>
                <div class="flex justify-end">
                    <button
                        class="action-button"
                        on:click|preventDefault={async () => {
                            await validateField('Firstname');
                            await validateField('Lastname');
                            await validateField('Email');
                            if (!$errors.Email && !$errors.Firstname && !$errors.Lastname) {
                                firstPart = false;
                            }
                        }}>Next</button
                    >
                </div>
            </div>
            <div class={firstPart && 'hidden'}>
                <div class="input-container">
                    <label class="block" for="FacebookID">Facebook ID</label>
                    <input
                        id="FacebookID"
                        class={$errors.FacebookID && 'contains-error'}
                        name="FacebookID"
                        placeholder="john_doe"
                        bind:value={$form.FacebookID}
                    />
                    {#if $errors.FacebookID}
                        <span class="error-info">{$errors.FacebookID}</span>
                    {/if}
                </div>
                <div class="input-container">
                    <label class="block" for="Username">Username</label>
                    <input
                        id="Username"
                        class={$errors.Username && 'contains-error'}
                        name="Username"
                        placeholder="johndoe"
                        bind:value={$form.Username}
                    />
                    {#if $errors.Username}
                        <span class="error-info">{$errors.Username}</span>
                    {/if}
                </div>
                <div class="input-container">
                    <label class="block" for="Password">Password</label>
                    <input
                        id="Password"
                        class={$errors.Password && 'contains-error'}
                        name="Password"
                        placeholder="Your strong password here"
                        type="password"
                        bind:value={$form.Password}
                    />
                    {#if $errors.Password}
                        <span class="error-info">{$errors.Password}</span>
                    {/if}
                </div>
                <div class="input-container">
                    <label class="block" for="ConfirmPassword">Confirm Password</label>
                    <input
                        id="ConfirmPassword"
                        class={$errors.ConfirmPassword && 'contains-error'}
                        name="ConfirmPassword"
                        placeholder="Confirm the password"
                        type="password"
                        bind:value={$form.ConfirmPassword}
                    />
                    {#if $errors.ConfirmPassword}
                        <span class="error-info">{$errors.ConfirmPassword}</span>
                    {/if}
                </div>
                <div class="flex justify-end">
                    <button class="action-button" on:click|preventDefault={() => (firstPart = true)}
                        >Back</button
                    >
                    <input
                        class="action-button"
                        type="submit"
                        value={`${$isSubmitting ? 'Registering...' : 'Register'}`}
                    />
                </div>
            </div>
            <div class="flex justify-center mt-5">
                <a href="/login">
                    <span class="other-form-link cursor-pointer">Already a member?</span>
                </a>
            </div>
        </form>
    </div>
</div>

// frontend/pages/register.tsx
import { NextPage } from "next";
import styles from "../styles/authform.module.scss";
import Logo from "../public/logo.png";
import { SubmitHandler, useForm } from "react-hook-form";
import Link from "next/link";
import { useState } from "react";
import Head from "next/head";

interface IFormInputs {
  firstName: string;
  lastName: string;
  email: string;
  username: string;
  facebook_id: string;
  password: string;
  confirm_password: string;
}
const Register: NextPage = () => {
  const {
    register,
    formState: { errors },
    handleSubmit,
    trigger,
    getValues,
  } = useForm<IFormInputs>();
  const onSubmit: SubmitHandler<IFormInputs> = () => {}; // TODO: implement registration
  const [isFirstPart, setIsFirstPart] = useState<boolean>(true);

  return (
    <div className={"flex justify-center items-center h-screen"}>
      <Head>
        <title>Register - NerdTree</title>
      </Head>
      <div className={styles["login-form"]}>
        <div>
          <img
            className={"bg-black rounded-full"}
            src={Logo.src}
            alt={"NerdTree Logo"}
          />
        </div>
        <Link href={"/"}>
          <h1 className={"cursor-pointer"}>Join NerdTree</h1>
        </Link>
        <form onSubmit={handleSubmit(onSubmit)}>
          {isFirstPart && (
            <>
              <div className={styles["input-container"]}>
                <label className={"block"}>First name</label>
                <input
                  className={errors.firstName && styles["contains-error"]}
                  type={"text"}
                  placeholder={"John"}
                  {...register("firstName", {
                    required: true,
                    minLength: 3,
                    maxLength: 255,
                    setValueAs(value) {
                      return value.trim();
                    },
                  })}
                />
                <span className={styles["error-info"]}>
                  {errors.firstName?.type == "maxLength" &&
                    "Maximum length for firstname is 255 characters"}
                  {errors.firstName?.type == "required" &&
                    "First name is required"}
                  {errors.firstName?.type == "minLength" &&
                    "Minimum length for firstname is 3 characters"}
                </span>
              </div>
              <div className={styles["input-container"]}>
                <label className={"block"}>Last name</label>
                <input
                  className={errors.lastName && styles["contains-error"]}
                  type={"text"}
                  placeholder={"Doe"}
                  {...register("lastName", {
                    required: true,
                    minLength: 3,
                    maxLength: 255,
                    setValueAs(value) {
                      return value.trim();
                    },
                  })}
                />
                <span className={styles["error-info"]}>
                  {errors.lastName?.type == "maxLength" &&
                    "Maximum length for lastname is 255 characters"}
                  {errors.lastName?.type == "required" &&
                    "Last name is required"}
                  {errors.lastName?.type == "minLength" &&
                    "Minimum length for lastname is 3 characters"}
                </span>
              </div>
              <div className={styles["input-container"]}>
                <label className={"block"}>Email</label>
                <input
                  className={errors.email && styles["contains-error"]}
                  type={"email"}
                  placeholder={"user@example.com"}
                  {...register("email", {
                    required: true,
                    pattern: /^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/g,
                    setValueAs(value) {
                      return value.trim();
                    },
                  })}
                />
                <span className={styles["error-info"]}>
                  {errors.email?.type == "pattern" && "Invalid email"}
                  {errors.email?.type == "required" && "Email is required"}
                </span>
              </div>
              <div className={"flex justify-end"}>
                <button
                  className={styles["action-button"]}
                  onClick={() => {
                    trigger().then((is_valid) => {
                      if (is_valid) {
                        setIsFirstPart(!isFirstPart);
                      }
                    });
                  }}
                >
                  Next
                </button>
              </div>
            </>
          )}
          {!isFirstPart && (
            <>
              <div className={styles["input-container"]}>
                <label className={"block"}>Username</label>
                <input
                  className={errors.username && styles["contains-error"]}
                  type={"text"}
                  placeholder={"johndoe1234"}
                  {...register("username", {
                    required: true,
                    minLength: 3,
                    maxLength: 25,
                    validate(value) {
                      return !value.includes(" ");
                    },
                  })}
                />
                <span className={styles["error-info"]}>
                  {errors.username?.type == "maxLength" &&
                    "Maximum length for username is 25 characters"}
                  {errors.username?.type == "required" &&
                    "Username is required"}
                  {errors.username?.type == "minLength" &&
                    "Minimum length for username is 3 characters"}
                  {errors.username?.type == "validate" &&
                    "Username cannot contain spaces"}
                </span>
              </div>
              <div className={styles["input-container"]}>
                <label className={"block"}>Password</label>
                <input
                  className={errors.password && styles["contains-error"]}
                  type={"password"}
                  placeholder={"Password"}
                  {...register("password", {
                    required: true,
                    minLength: 8,
                    maxLength: 80,
                  })}
                />
                <span className={styles["error-info"]}>
                  {errors.password?.type == "maxLength" &&
                    "Maximum length for password is 80 characters"}
                  {errors.password?.type == "required" &&
                    "Password is required"}
                  {errors.password?.type == "minLength" &&
                    "Minimum length for password is 8 characters"}
                </span>
              </div>
              <div className={styles["input-container"]}>
                <label className={"block"}>Confirm password</label>
                <input
                  className={
                    errors.confirm_password && styles["contains-error"]
                  }
                  type={"password"}
                  placeholder={"Confirm password"}
                  {...register("confirm_password", {
                    required: true,
                    minLength: 8,
                    maxLength: 80,
                    validate: (value) => value == getValues("password"),
                  })}
                />
                <span className={styles["error-info"]}>
                  {errors.confirm_password?.type == "maxLength" &&
                    "Maximum length for password is 80 characters"}
                  {errors.confirm_password?.type == "required" &&
                    "Password is required"}
                  {errors.confirm_password?.type == "minLength" &&
                    "Minimum length for password is 8 characters"}
                  {errors.confirm_password?.type == "validate" &&
                    "Passwords must be equal"}
                </span>
              </div>
              <div className={"flex justify-end"}>
                <button
                  className={styles["action-button"]}
                  onClick={() => setIsFirstPart(!isFirstPart)}
                >
                  Back
                </button>
                <input
                  className={styles["action-button"]}
                  type={"submit"}
                  value={"Register"}
                />
              </div>
            </>
          )}
          <div className={"flex justify-center"}>
            <Link href={"/login"}>
              <span className={`${styles["other-form-link"]} cursor-pointer`}>
                Already a member?
              </span>
            </Link>
          </div>
        </form>
      </div>
    </div>
  );
};

export default Register;
